version: '3.3'
services:
  mapview-db:
    image: mysql:8.0
    container_name: mapview-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mapview
    ports:
      - "3306:3306"
    networks:
      - mapview-net
    volumes:
      - mysql-data:/var/lib/mysql

  api-mapview:
    depends_on:
      - mapview-db
    container_name: api-mapview
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mapview-db:3306/mapview
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
   
    ports:
      - "8081:8081"
    networks:
      - mapview-net

volumes:
  mysql-data:

networks:
  mapview-net:
    driver: bridge
