version: '3.3'
services:
  mapview-db:
    image: mysql:8.0
    container_name: mapview-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mapview
    ports:
      - "3306:3306"
    networks:
      - mapview-net
    volumes:
      - mysql-data:/var/lib/mysql

  api-gateway:
    container_name: api-gateway
    build:
      context: ./gateway
    ports:  
      - "8000:8000"
    networks:
      - mapview-net

  api-mapview:
    depends_on:
      - mapview-db
    container_name: api-mapview
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mapview-db:3306/mapview
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      spring.security.oauth2.resourceserver.jwt.issuer-uri: https://login.microsoftonline.com/0ae51e19-07c8-4e4b-bb6d-648ee58410f4/v2.0
      spring.servlet.multipart.max-file-size: 20MB
      spring.servlet.multipart.max-request-size: 20MB
      server.error.include-stacktrace: never
      logging.level.org.springframework.web: DEBUG
      logging.level.org.springframework.security: DEBUG
      spring.web.servlet.logRequestDetails: true
      myapp.jwtUri: https://login.microsoftonline.com/0ae51e19-07c8-4e4b-bb6d-648ee58410f4/discovery/v2.0/keys
   
    ports:
      - "9000:9000"
    networks:
      - mapview-net

  #angular-app:
    #build:
      #context: ./frontend # Caminho onde está o Dockerfile do Angular
    #container_name: angular-app
    #ports:
     # - "4200:4200"  # Mapeia a porta 4200 do container para a 4200 da máquina
   # networks:
     # - mapview-net

volumes:
  mysql-data:

networks:
  mapview-net:
    driver: bridge
